baseURL = "https://tech.yaltopia.com"
languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator-hugo"
summaryLength = 10
# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID
enableGitInfo = false
pygmentsCodeFences = true
# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
[[Params.listeLangues]]
code = "amh"

[[Params.listeLangues]]
code = "en"
# meta data
author = "Themefisher"
description = "This is meta description"

# Gestion des langues : FR / EN / NL / DE
[Languages]

############ 1 - Site en Amh
[Languages.amh]
weight = 1
languageCode = "Amh-amh"
title = "YaltopyaTech"
dateFormat = "2 January 2006"
home = "Home"
logo = "images/Fixed1.png"
menufixed = false
footerDescription = ""
footerServiceTitle = ""
footerQuicklinkTitle = ""
footerAboutTitle = ""
footerSubscribeTitle = "በቅርብ ቀን"

# Hero Area Section
[Languages.amh.params.hero]
enable = false
heading = ""
description = ""
button = true
btnText = "በቅርብ ቀን"
btnURL = "https://www.youtube.com/channel/UC_4173FO268_5MMJMZAoo6A"
videoThumb = "images/slider/video-thumb.jpg"
videoURL = "https://www.youtube.com/embed/SJRIORWkE0w"

# About 2 Section
[Languages.amh.params.aboutSm]
enable = false
title = ""
description = ""
[Languages.amh.params.ComingSoon]
enable = true
title = ""
description= "በቅርቡ በአማርኛ እንቀርባለን።"
# Blog Section On Homepage
[Languages.amh.params.blog]
enable = false
topTitle = "OUR UNTOLD STORY"
title = ""
subtitle = ""

# Contact Section
[Languages.amh.params.contact]
enable = false
topTitle = "DROP US A NOTE"
title = "Contact Us."
subtitle = ""
address = "We're working on it :)"
phone = " +2519 2903 3293"
second = " +2519 8303 2475"
facebook = "https://www.facebook.com/Yaltopia"
twitter = "https://twitter.com/yaltopyatech"
youtube = "https://www.youtube.com/channel/UC_4173FO268_5MMJMZAoo6A"
mapLatitude = "51.507351"
mapLongitude = "-0.127758"
mapMarker = "images/marker.png"

# Call to Action Section on About Page
[Languages.amh.params.cta]
enable = false
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = ""
subtitle = ""
btnText = ""

############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "YaltopyaTech"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/Fixed1.png"
menufixed = false
footerDescription = "It is our goal in this day and age to help introduce more people to technology. The constant change in the tech world influences and changes everyone’s life with or without them realizing it. But this change can be both for good or for bad. Our goal is for the change to bring a positive impact to your lives."
footerServiceTitle = "Places"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"

# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable = true
heading = "We follow up on the daily trend to make sure you are informed"
description = " The world of tech is a fast changing one and one that is unforgiving to those that don't follow up on daily events. But fret not cause our content strives to keep you informed and make the right decisions be it on buying a smartphone, console, laptop, Desktop or even a digital fridge."
button = true
btnText = "Subscribe"
btnURL = "https://www.youtube.com/channel/UC_4173FO268_5MMJMZAoo6A"
videoThumb = "images/slider/video-thumb.jpg"
videoURL = "https://www.youtube.com/embed/SJRIORWkE0w"

# About 2 Section
[Languages.en.params.aboutSm]
enable = true
title = "We have explored the digital landscape with passion for a long time"
description = "We are always willing to explore new opprtunties so be sure to contact us. If you also have any topics you  <br> would like to be covered by us be sure to send them! "

# Blog Section On Homepage
[Languages.en.params.blog]
enable = true
topTitle = "OUR UNTOLD STORY"
title = "Blog."
subtitle = ""

# Contact Section
[Languages.en.params.contact]
enable = true
topTitle = "DROP US A NOTE"
title = "Contact Us."
subtitle = "Please Feel Free to Drop Us a Note!"
address = "We're working on it :)"
phone = " +2519 2903 3293"
second = " +2519 8303 2475"
facebook = "https://www.facebook.com/Yaltopia"
twitter = "https://twitter.com/yaltopyatech"
youtube = "https://www.youtube.com/channel/UC_4173FO268_5MMJMZAoo6A"
mapLatitude = "38.7624143"
mapLongitude = "9.0400256"
mapMarker = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's Create Something Together"
subtitle = "We are always willing to explore new opprtunties so be sure to contact us. If you also have any topics you  <br> would like to be covered by us be sure to send them! "
btnText = "Contact Us"
link = "en/contact/"

# Site Menus
[menu]

# Navbar Menus
[[menu.nav]]
name = "about"
url = "about"
weight = 2

[[menu.nav]]
name = "video"
url = "video"
weight = 3

[[menu.nav]]
name = "service"
url = "service"
weight = 4

[[menu.nav]]
name = "blog"
url = "blog"
weight = 5

[[menu.nav]]
name = "forum"
url = "https://forum-tech.yaltopia.com/phpbb/"
weight = 6

[[menu.nav]]
name = "contact"
url = "contact"
weight = 7

# Footer Service Menu
[[menu.places]]
name = "video"
url = "video"
weight = 1

[[menu.places]]
name = "cont_us"
url = "contact"
weight = 2

[[menu.places]]
name = "blog"
url = "blog"
weight = 3

[[menu.places]]
name = "forum"
url = "https://forum-tech.yaltopia.com/phpbb/"
weight = 4

# Footer Quick links Menu
[[menu.quicklink]]
name = "partners"
url = "about"
weight = 1

[[menu.quicklink]]
name = "about"
url = "about"
weight = 2
